Makefile
README.md
src/closet_search/settings.py

RDSの設定をsettings.pyに設定。
（セキュリティ上詳しいことはenvファイルに記載しているので詳細な情報はリポジトリ上に挙げていない。）
+
Ruffのコマンドを簡易的に設定できるようにMakefileの作成
および
READMEにコマンド類を説明

RDS設定とRuffエイリアス設定

---

src/closet_search/settings.py

fix:S3関連の設定をコメントアウトで追記(一部修正)

---

.github/workflows/deploy.yml

自動デプロイに失敗したので
今度はBastion経由のSSHをGitHub Actionsに組み込むように設定

fix:再度自動デプロイできるように設定

---

.github/workflows/deploy.yml

fix:インバウンドルールを変更

---

.github/workflows/deploy.yml

インバウンドルール変更

---

.gitignore
README.md
docker-compose.yml

以下の設定を修正
メンターからの指摘により以下の部分を修正
・pyc ファイル等をGit管理対象外にした。
・migrate  ビルド起動時に自動で実行するように設定
　（それに伴い、READMEを一部修正)

fix:設定周りの修正

---

.github/workflows/NotyfyPR.yml

Mattermostの内向きWebhookを活用して通知を行うためのymlファイルを追加しました。

プルリクエストオープン時、Mattermostに通知するよう設定

---

.github/workflows/NotyfyPR.yml

NotyfyPR.ymlのインデントを修正

---

README.md

fix:Djangoプロジェクト削除コマンド追記

---

README.md

https://github.com/summer-hackathon-c/closet-search/issues/73

独自ドメインのURLをREADMEに追記

---

.github/workflows/NotyfyPR.yml

NotfyPRのYAMLを修正

---

.github/workflows/deploy.yml

アベイラビリティーゾーン1-a と1-cに設定しているプライベートサーバに自動デプロイできるように
deploy.ymlを修正

二つのプライベートサーバーに自動デプロイできるように設定

---

docker-compose.prod.yml

docker-compose.prod.ymlの最後のdbの文言を削除

docoker-composeのdbの文言を削除

---

docker-compose.prod.yml

docker-compose.prod.ymlにvolumesを追記

docoker-composeにvolumesを再追記

---

src/items/templates/items/create.html
src/items/templates/items/detail.html
src/items/templates/items/edit.html
src/items/templates/items/index.html
src/templates/registration/login.html
src/templates/registration/signup.html

MVP機能の、ログイン・ユーザー登録、アイテム周りのテンプレートに、最低限のオブジェクト表示を追加しました。
バックエンド開発で使うため、簡易的に用意したものです。
それぞれのテンプレートは、今後のタスクで細かく実装していきます。
- `src/items/templates/items/create.html`
- `src/items/templates/items/index.html`
- `src/items/templates/items/detail.html`
- `src/items/templates/items/edit.html`
- `src/templates/registration/login.html`
- `src/templates/registration/signup.html`

最低限のtemplate表示を追加

---

.github/workflows/deploy.yml

踏み台サーバーを廃止してAWS Systems Managerを導入した。
それに伴い、deploy.ymlのコードを修正

fix:AWS Systems Manager導入

---

.github/workflows/deploy.yml

fix:AWS Systems Manager修正

---

src/closet_search/settings.py
src/items/urls.py
src/items/views.py

概要
===============================
アイテム一覧表示の機能追加
お手数ですが、レビューをお願いいたします。
対応内容
================================
①src/closet_search/settings.py
　ログインしていないユーザーは、ログイン画面へ戻る実装
②src/items/urls.py
　pathへuser_idを追記
③src/items/views.py
　アイテム一覧表示の実装。

fix:アイテム一覧表示の機能追加

---

src/closet_search/settings.py

fix:CSRFの設定を追記

---

src/items/models.py
src/items/templates/items/create.html
src/items/templates/items/detail.html
src/items/templates/items/index.html

一覧画面から詳細画面に画面遷移するリンクを追加
ついでに一覧画面に戻るリンクも追加
https://www.loom.com/share/f1cc62bb04b14a72bdc886731df29740

一覧画面から詳細画面に画面遷移するように設定

---

src/closet_search/settings.py

fix:DATABASE_ROUTERSを修正

---

src/closet_search/db_routers.py
src/closet_search/settings.py

setting.pyのDATABASE_ROUTERSのURL名を変更

DATABASE_ROUTERS

---

src/closet_search/urls.py

ターゲットグループのhealthcheckを
200 OKにするように設定

fix:ヘルスチェック

---

src/closet_search/settings.py
src/closet_search/storage_backends.py

レイアウト崩れ対策で新たにstorage_backends.pyを作成。
その後にsettings.pyを修正

fix:staticとmediaを分離

---

src/static/css/base_auth.css
src/static/css/signup.css
src/static/js/password_eye.js
src/templates/base_auth.html
src/templates/registration/login.html
src/templates/registration/signup.html

目のアイコンを設定するために
base_auth.htmlにFont Awesomeを適用
目のアイコンで表示非表示を切り替えるように
password_eye.jsを追加
ユーザー登録画面からログイン画面に戻るようにリンクを追加
動画
https://www.loom.com/share/eaf127941a254c3c9a2a57f38140ea3d

目のアイコン押下でパスワードの表示と非表示を切替できるように設定

---

src/closet_search/storage_backends.py

fix:custom_domainを削除
